name: publish

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    permissions:
      contents: read
  publish-npm:
    needs: [tests]
    uses: brickhouse-tech/.github/.github/workflows/publish.yml@3c0bca8e1e161a6f61aee72413611b6fca239974 # pinned SHA
    permissions:
      contents: read
      id-token: write
    secrets: inherit
